name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar test

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ivanbot-log-processor.jar
          path: build/libs/*.jar

      - name: Delete old tag
        run: |
          if git rev-parse --verify latest >/dev/null 2>&1; then
            git tag -d latest
          fi
          if git ls-remote --tags origin latest | grep latest >/dev/null 2>&1; then
            git push origin :refs/tags/latest
          fi
      - name: Set up Git identity
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Create or Update tag 'latest'
        run: |
          git tag -fa latest -m "Update latest"
          git push origin latest

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Release latest
          draft: false
          prerelease: false
          files: build/libs/ivanbot-log-processor.jar

      - name: Cleanup old packages
        if: ${{ github.event_name == 'push' }}
        run: ./gradlew clean

  cleanup:
    runs-on: ubuntu-latest
    needs: gradle
    steps:
      - name: Remove package versions
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '2 days'
          skip-recent: 2
